'use strict';
var budgetRows=[],expenseColumns=[],budgetsLoaded=false,dataLoaded=false,lastSync=null,readOnlyOffline=false,loadingWorkbook=false,workbookIdle=Promise.resolve(),finishLoad=null;
function escapeHtml(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function sameRaw(a,b){if(!a||!b)return false;var n=Math.max(a.length,b.length);for(var i=0;i<n;i++)if(String(a[i]==null?'':a[i])!==String(b[i]==null?'':b[i]))return false;return true;}
function selectedKey(){return selAno+'-'+String(selMes).padStart(2,'0');}
function excel(){return new ExcelClient({driveId:DRIVE_ID,fileId:FILE_ID},getToken);}
function fieldName(s){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();}
var knownFields={date:'date',time:'time',merchant:'merchant',amount:'amount',card:'card',latitude:'lat',longitude:'lng',obs:'obs',categoria:'cat_override'};
function normalizeRow(r){var v=r.values[0],o={rowIndex:r.index,rawValues:v};expenseColumns.forEach(function(c,i){var k=knownFields[fieldName(c.name)];if(k)o[k]=v[i];});o.date=parseExcelDate(o.date);o.amount=typeof o.amount==='number'?o.amount:String(o.amount==null?'':o.amount);['time','merchant','card','obs','cat_override'].forEach(function(k){o[k]=String(o[k]||'').trim();});o.lat=Number(o.lat)||0;o.lng=Number(o.lng)||0;return o;}
function rowValues(row){return expenseColumns.map(function(c,i){var k=knownFields[fieldName(c.name)];return k?(row[k]===undefined?'':row[k]):(row.rawValues&&row.rawValues[i]!==undefined?row.rawValues[i]:'');});}
async function ensureExtraColumns(){var client=excel();for(var name of ['Obs','Categoria']){if(!expenseColumns.some(function(c){return fieldName(c.name)===fieldName(name);})){await client.request('/tables/'+TABLE+'/columns/add','POST',{name:name});expenseColumns=await client.collection('/tables/'+TABLE+'/columns');}}}
function parseBudgets(rows){return rows.filter(function(r){return r.values[0][0];}).map(function(r){return {month:String(r.values[0][0]),budget:r.values[0][1],updatedAt:r.values[0][2],rowIndex:r.index};});}
async function loadWorkbook(){
  if(loadingWorkbook){await workbookIdle;return loadWorkbook();}loadingWorkbook=true;workbookIdle=new Promise(function(resolve){finishLoad=resolve;});hideErr();
  try{
    if(!navigator.onLine){await showOffline();return false;}
    var client=excel();
    expenseColumns=await client.collection('/tables/'+TABLE+'/columns');
    for(var required of ['date','time','merchant','amount','card','latitude','longitude'])if(!expenseColumns.some(function(c){return fieldName(c.name)===required;}))throw new Error('Coluna ausente na tabela Gastos: '+required);
    var raw=await client.rows(TABLE),newBudgets=[];
    try{newBudgets=parseBudgets(await client.rows('Orcamentos'));}catch(e){if(e.status!==404)throw e;}
    allRows=raw.map(normalizeRow).filter(function(r){return r.merchant;});budgetRows=newBudgets;budgetsLoaded=true;dataLoaded=true;readOnlyOffline=false;lastSync=new Date().toISOString();
    await saveSnapshot();renderMonth();updateSyncLabel();return true;
  }catch(e){
    updateSyncLabel(true);showErr('Não foi possível atualizar. '+e.message);
    if(e.status===401||e.name==='InteractionRequiredAuthError'||e.errorCode==='interaction_required'||e.errorCode==='login_required'){msalApp.acquireTokenRedirect({scopes:SCOPES,account:account,redirectUri:REDIRECT});}
    return false;
  }finally{loadingWorkbook=false;finishLoad();}
}
function updateSyncLabel(failed){var el=document.getElementById('lastUpdate');el.textContent=lastSync?((readOnlyOffline||failed?'Cópia salva · ':'Atualizado · ')+new Date(lastSync).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})):'Aguardando sincronização';}
function renderBalanceMonth(){
  updateMonthNav();var s=Finance.summary(allRows,budgetRows,selectedKey());window.currentSummary=s;
  var ready=dataLoaded&&budgetsLoaded&&s.budgetCents!==null&&s.complete;
  document.getElementById('hTotal').textContent=ready?Finance.format(s.availableCents):'—';
  document.getElementById('hTotal').style.color=ready&&s.availableCents<0?'#ff453a':'#fff';
  document.getElementById('saldoLabel').textContent=ready&&s.availableCents<0?'Orçamento excedido':'Disponível neste mês';
  document.getElementById('dailyAmount').textContent=ready&&s.dailyCents!==null?'R$ '+Finance.format(s.dailyCents):'—';
  document.getElementById('dailyLabel').textContent=s.daysRemaining?' por dia · '+s.daysRemaining+' dias, incluindo hoje':' mês encerrado';
  document.getElementById('budgetAmount').textContent=s.budgetCents===null?'Não definido':'R$ '+Finance.format(s.budgetCents);
  document.getElementById('spentAmount').textContent='R$ '+Finance.format(s.spentCents);
  document.getElementById('sToday').textContent='R$ '+Finance.format(s.todayCents);document.getElementById('sCount').textContent=s.rows.length;document.getElementById('sAvg').textContent='R$ '+Finance.format(s.rows.length?Math.round(s.spentCents/s.rows.length):0);
  var notes=[];
  if(!dataLoaded)notes.push('Entre e sincronize para calcular seu saldo.');
  else if(s.budgetCents===null)notes.push('Defina o orçamento para começar.');
  if(s.unknownDates)notes.push(s.unknownDates+' registros sem ano. Confirme o ano em Ajustar orçamento ou corrija as datas no Excel. O saldo fica oculto até isso ser resolvido.');
  if(s.invalidRows)notes.push(s.invalidRows+' registros com data ou valor inválidos. Corrija-os no Excel para liberar o saldo.');
  if(s.incompleteInstallments)notes.push('Há parcelamentos incompletos no Excel. Retome a operação ou confira as parcelas para liberar o saldo.');
  if(s.duplicateBudgets)notes.push('Há linhas repetidas na tabela Orcamentos. Confira no Excel para liberar o saldo.');
  if(s.possibleDuplicates)notes.push(s.possibleDuplicates+' possíveis duplicatas neste mês. Elas continuam incluídas; confira antes de excluir.');
  if(s.inherited)notes.push('Orçamento repetido do último mês configurado.');
  if(readOnlyOffline)notes.push('Sem sincronização: mostrando a última cópia salva. Para gravar, conecte-se e entre novamente.');
  if(pendingInstallment())notes.push('Há um parcelamento em andamento. Use Retomar parcelamento abaixo.');
  document.getElementById('qualityNote').textContent=notes.join('\n');
  document.getElementById('txCount').textContent=s.rows.length+' no mês';window._txs=s.rows;
  var area=document.getElementById('txArea');
  if(!s.rows.length){area.innerHTML='<div class="empty">Nenhum lançamento com data confirmada neste mês.</div>';}
  else {area.innerHTML='<div class="txlist">'+s.rows.map(function(tx,i){var cat=getCat(tx.merchant,tx.cat_override);return '<div class="txitem" role="button" tabindex="0" data-tx="'+i+'"><div class="txicon" style="background:'+cat.bg+'">'+cat.e+'</div><div class="txinfo"><div class="txmerch">'+escapeHtml(tx.merchant)+'</div><div class="txmeta">'+escapeHtml(tx.date)+(tx.time?' · '+escapeHtml(tx.time):'')+'</div></div><div class="txright"><div class="txamt">'+(tx.cents<0?'+':'−')+' R$ '+Finance.format(Math.abs(tx.cents))+'</div><div class="txcard">'+escapeHtml(/^\d{4}$/.test(tx.card)?'Itaú · '+tx.card:tx.card)+'</div></div></div>';}).join('')+'</div>';area.querySelectorAll('[data-tx]').forEach(function(el){el.onclick=function(){openDetail(s.rows[+el.dataset.tx]);};el.onkeydown=function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();el.click();}};});}
  var resume=document.getElementById('resumeInstallment');if(resume)resume.remove();
  if(pendingInstallment()){var b=document.createElement('button');b.id='resumeInstallment';b.className='action-btn';b.textContent='Retomar parcelamento';b.onclick=function(){resumeInstallment().catch(function(e){showErr(e.message);});};document.querySelector('.utility').appendChild(b);}
}
function closeV2Modal(id){document.getElementById(id).classList.remove('open');}
function requireWrite(){if(readOnlyOffline||!account||!navigator.onLine)throw new Error('Conecte-se à internet e entre com Microsoft para salvar.');if(!dataLoaded)throw new Error('Atualize os dados antes de salvar.');}
function openBudget(){document.getElementById('budgetPeriod').textContent=MONTHS[selMes-1]+' '+selAno;var b=Finance.budgetFor(budgetRows,selectedKey());document.getElementById('budgetInput').value=b?Finance.format(b.cents):'';document.getElementById('legacyYearInput').value=Finance.legacyYear(budgetRows)||'';document.getElementById('budgetStatus').textContent='';document.getElementById('budgetModal').classList.add('open');}
async function upsertBudget(month,budget){var client=excel(),rows=parseBudgets(await client.rows('Orcamentos')),found=rows.filter(function(r){return r.month===month;});if(found.length>1)throw new Error('Há mais de um orçamento para '+month+'. Corrija a tabela Orcamentos.');var values=[month,budget,new Date().toISOString()];return found.length?client.patch('Orcamentos',found[0].rowIndex,values):client.add('Orcamentos',[values]);}
async function saveBudget(){
  var status=document.getElementById('budgetStatus'),btn=document.getElementById('saveBudgetBtn');btn.disabled=true;
  try{requireWrite();var value=Finance.cents(document.getElementById('budgetInput').value),legacy=document.getElementById('legacyYearInput').value.trim();if(value===null||value<0)throw new Error('Informe um orçamento válido, zero ou maior.');if(legacy&&(!/^\d{4}$/.test(legacy)||+legacy<1900||+legacy>2200))throw new Error('Informe o ano completo.');status.textContent='Salvando no Excel…';await excel().ensureBudgets();await upsertBudget(selectedKey(),value/100);if(legacy)await upsertBudget('__legacy_year__',Number(legacy));else {var old=parseBudgets(await excel().rows('Orcamentos')).find(function(r){return r.month==='__legacy_year__';});if(old)await excel().remove('Orcamentos',old.rowIndex);}if(!await loadWorkbook())throw new Error('A gravação foi enviada, mas a atualização falhou. Atualize antes de repetir.');closeV2Modal('budgetModal');}
  catch(e){status.textContent=e.message+' Se houve falha de conexão após enviar, atualize antes de tentar novamente.';}finally{btn.disabled=false;}
}
function openManual(){var today=Finance.parts();document.getElementById('manualDate').value=today.year+'-'+String(today.month).padStart(2,'0')+'-'+String(today.day).padStart(2,'0');document.getElementById('manualAmount').value='';document.getElementById('manualMerchant').value='';document.getElementById('manualCategory').innerHTML='<option value="">Automática</option>'+CATS.concat([{label:'Outros'}]).map(function(c){return '<option>'+escapeHtml(c.label)+'</option>';}).join('');document.getElementById('manualStatus').textContent='';document.getElementById('manualModal').classList.add('open');}
async function saveManual(){var status=document.getElementById('manualStatus'),btn=document.getElementById('saveManualBtn');btn.disabled=true;try{requireWrite();var value=Finance.cents(document.getElementById('manualAmount').value),dt=Finance.date(document.getElementById('manualDate').value),merchant=document.getElementById('manualMerchant').value.trim(),payment=document.getElementById('manualCard').value.trim();if(!value||value<0||!dt||!merchant||!payment)throw new Error('Confira valor, data, descrição e pagamento.');await ensureExtraColumns();if(document.getElementById('manualType').value==='refund')value=-value;await excel().add(TABLE,[rowValues({date:dt.display,time:new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date()),merchant:merchant,amount:value/100,card:payment,obs:'Lançamento manual · '+new Date().toISOString(),cat_override:document.getElementById('manualCategory').value})]);if(!await loadWorkbook())throw new Error('Lançamento enviado. Atualize para confirmar antes de repetir.');closeV2Modal('manualModal');}catch(e){status.textContent=e.message+' Se a conexão caiu depois do envio, confira o Excel antes de repetir.';}finally{btn.disabled=false;}}
async function deleteCurrent(){try{requireWrite();if(!currentTx||!confirm('Excluir este lançamento do Excel? Essa ação altera o histórico.'))return;var original=currentTx,raw=await excel().rows(TABLE),row=raw.find(function(r){return r.index===original.rowIndex;});if(!row||!sameRaw(row.values[0],original.rawValues))throw new Error('O lançamento mudou. Atualize e abra-o novamente.');await excel().remove(TABLE,original.rowIndex);closeDetail();await loadWorkbook();}catch(e){showErr(e.message);}}
function operationKey(){return 'saldo-livre-parcelamento-'+(account?account.homeAccountId:'');}
function pendingInstallment(){try{return account&&JSON.parse(localStorage.getItem(operationKey())||'null');}catch(_){return null;}}
async function saveInstallments(){var btn=document.getElementById('mBtnOk');btn.disabled=true;btn.textContent='Salvando…';try{requireWrite();if(pendingInstallment())throw new Error('Retome o parcelamento anterior antes de iniciar outro.');await ensureExtraColumns();var n=Number(document.getElementById('mInput').value),plan=Finance.installments(currentTx.amount,n,currentTx.date,Finance.legacyYear(budgetRows));var op={id:crypto.randomUUID(),original:currentTx,plan:plan,base:currentTx.merchant,stage:'new'};localStorage.setItem(operationKey(),JSON.stringify(op));await resumeInstallment();fecharModal();closeDetail();}catch(e){showErr(e.message+' Atualize os dados e use Retomar parcelamento; não recrie a compra.');}finally{btn.textContent='Confirmar';btn.disabled=false;renderMonth();}}
var resumingInstallment=false;
async function resumeInstallment(){
  if(resumingInstallment)return;resumingInstallment=true;
  try{requireWrite();var op=pendingInstallment();if(!op)return;var client=excel(),mark='[SL:'+op.id+']',raw=await client.rows(TABLE),rows=raw.map(normalizeRow);
    var first=rows.find(function(r){return r.obs.includes(mark)&&r.merchant===op.base+' (1/'+op.plan.length+')';});
    if(!first){if(op.stage!=='new')throw new Error('A primeira parcela não foi localizada. Confira o Excel.');var source=rows.find(function(r){return r.rowIndex===op.original.rowIndex;});if(!source||!sameRaw(source.rawValues,op.original.rawValues))throw new Error('A compra original mudou. Confira o Excel antes de retomar.');await client.patch(TABLE,source.rowIndex,rowValues(Object.assign({},source,{date:op.plan[0].date,amount:op.plan[0].amount,merchant:op.base+' (1/'+op.plan.length+')',obs:(source.obs?source.obs+'\n':'')+mark})));}
    op.stage='first-written';localStorage.setItem(operationKey(),JSON.stringify(op));
    // Read-before-add makes retries recoverable even after a response is lost.
    rows=(await client.rows(TABLE)).map(normalizeRow);var missing=[];
    for(var i=1;i<op.plan.length;i++){var merchant=op.base+' ('+(i+1)+'/'+op.plan.length+')';var existing=rows.filter(function(r){return r.obs.includes(mark)&&r.merchant===merchant;});if(existing.length>1)throw new Error('Parcela duplicada detectada. Confira o Excel.');if(!existing.length)missing.push(rowValues(Object.assign({},op.original,{rawValues:undefined,date:op.plan[i].date,amount:op.plan[i].amount,merchant:merchant,obs:(op.original.obs?op.original.obs+'\n':'')+mark})));}
    if(missing.length)await client.add(TABLE,missing);
    var verified=(await client.rows(TABLE)).map(normalizeRow);for(var j=0;j<op.plan.length;j++){var matches=verified.filter(function(r){return r.obs.includes(mark)&&r.merchant===op.base+' ('+(j+1)+'/'+op.plan.length+')';});if(matches.length!==1||Finance.cents(matches[0].amount)!==Finance.cents(op.plan[j].amount)||matches[0].date!==op.plan[j].date)throw new Error('Ainda não foi possível confirmar todas as parcelas.');}
    localStorage.removeItem(operationKey());await loadWorkbook();
  }finally{resumingInstallment=false;}
}
function exportCsv(){if(!dataLoaded){showErr('Sincronize ou abra a cópia offline primeiro.');return;}var quote=function(v){var s=String(v==null?'':v);if(/^[=+@-]/.test(s.trimStart())&&typeof v!=='number')s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};var lines=[['Data','Hora','Descrição','Valor','Pagamento','Categoria','Observações']].concat(allRows.map(function(r){return [r.date,r.time,r.merchant,r.amount,r.card,r.cat_override||getCat(r.merchant).label,r.obs];}));var blob=new Blob(['\ufeff'+lines.map(function(r){return r.map(quote).join(';');}).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='gastos-'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(function(){URL.revokeObjectURL(url);},1000);}
function openStore(){return new Promise(function(resolve,reject){var req=indexedDB.open('saldo-livre',1);req.onupgradeneeded=function(){req.result.createObjectStore('snapshots');};req.onsuccess=function(){resolve(req.result);};req.onerror=function(){reject(req.error);};});}
async function storeSnapshot(mode,key,value){var db=await openStore();try{return await new Promise(function(resolve,reject){var tx=db.transaction('snapshots',mode),store=tx.objectStore('snapshots'),req=mode==='readonly'?store.get(key):store.put(value,key),result;req.onsuccess=function(){result=req.result;};tx.oncomplete=function(){resolve(result);};tx.onerror=function(){reject(tx.error);};});}finally{db.close();}}
async function saveSnapshot(){if(!account)return;try{await storeSnapshot('readwrite',account.homeAccountId,{rows:allRows,budgets:budgetRows,columns:expenseColumns,lastSync:lastSync});localStorage.setItem('saldo-livre-last-account',account.homeAccountId);}catch(e){showErr('Dados atualizados, mas a cópia offline não pôde ser salva: '+e.message);}}
async function initOffline(){try{var id=localStorage.getItem('saldo-livre-last-account');if(id&&await storeSnapshot('readonly',id))document.getElementById('offlineBtn').style.display='inline-block';}catch(_){}if('serviceWorker' in navigator)navigator.serviceWorker.register('./service-worker.js').catch(function(e){console.warn('PWA indisponível',e);});window.addEventListener('online',function(){if(account)loadData();});window.addEventListener('offline',function(){readOnlyOffline=true;updateSyncLabel();renderMonth();});document.addEventListener('visibilitychange',function(){if(!document.hidden&&account&&navigator.onLine&&(!lastSync||Date.now()-Date.parse(lastSync)>60000))loadData();});setInterval(function(){if(dataLoaded&&!document.hidden){var p=Finance.parts();if(selectedKey()!==Finance.monthKey(p)&&document.getElementById('mnLabel').dataset.auto==='yes'){selMes=p.month;selAno=p.year;}renderMonth();}},60000);}
async function showOffline(){try{var id=account?account.homeAccountId:localStorage.getItem('saldo-livre-last-account'),snapshot=id&&await storeSnapshot('readonly',id);if(!snapshot)throw new Error('Nenhuma cópia salva neste aparelho.');allRows=snapshot.rows;budgetRows=snapshot.budgets;expenseColumns=snapshot.columns;lastSync=snapshot.lastSync;dataLoaded=true;budgetsLoaded=true;readOnlyOffline=true;document.getElementById('overlay').style.display='none';renderMonth();updateSyncLabel();}catch(e){showErr(e.message);}}
async function signOut(){try{var id=account?account.homeAccountId:localStorage.getItem('saldo-livre-last-account');if(id){var db=await openStore();await new Promise(function(resolve,reject){var tx=db.transaction('snapshots','readwrite');tx.objectStore('snapshots').delete(id);tx.oncomplete=resolve;tx.onerror=function(){reject(tx.error);};});db.close();}localStorage.removeItem('saldo-livre-last-account');allRows=[];budgetRows=[];dataLoaded=false;budgetsLoaded=false;lastSync=null;renderMonth();if(msalApp&&account)await msalApp.logoutRedirect({account:account,postLogoutRedirectUri:REDIRECT});else location.reload();}catch(e){showErr('Não foi possível sair: '+e.message);}}
